### ISSUE TITLE
我今天刚买的你的教程，中间出错了

### ISSUE THREAD

**Issue by wifidu** [zhanghong/tpadmin#1]
我在 **后台模块搭建** 出问题了，我是Debian系统。输入localhost/admin打不开后台。前面都是成功的，我用的是localhost，能打开首页。

**Comment by zhanghong** [comment]
麻烦打开一下Debug把错误信息贴出来我看一下

**Comment by alongasong** [comment]
我也发现了错误……
我的样例发布在这里：

http://thinkbbs.cacbc.net/index.php/admin


[0] ClassNotFoundException in Container.php line 442
类不存在: \tpadmin\controller\Auth\Passport

                }

                $constructor = $reflect->getConstructor();

                $args = $constructor ? $this->bindParams($constructor, $vars) : [];

                return $reflect->newInstanceArgs($args);

            } catch (ReflectionException $e) {
                throw new ClassNotFoundException('class not exists: ' . $class, $class);
            }
        }

        /**
         * 绑定参数
         * @access protected
         * @param  \ReflectionMethod|\ReflectionFunction $reflect 反射类
         * @param  array                                 $vars    参数
         * @return array

Call Stack

    in Container.php line 442
    at Container->invokeClass('\tpadmin\controller\...') in Container.php line 364
    at Container->invokeMethod(['\tpadmin\controller\...', 'login'], []) in Container.php line 411
    at Container->invoke(['\tpadmin\controller\...', 'login'], []) in Callback.php line 23
    at Callback->exec() in Dispatch.php line 168
    at Dispatch->run() in App.php line 432
    at App->think\{closure}(object(Request), object(Closure), null)
    at call_user_func_array(object(Closure), [object(Request), object(Closure), null]) in Middleware.php line 185
    at Middleware->think\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Middleware.php line 130
    at Middleware->dispatch(object(Request)) in App.php line 435
    at App->run() in index.php line 21

Environment Variables
GET Dataempty
POST Dataempty
Filesempty
Cookies thinkphp_show_page_trace 	0|0
language 	zh-cn
currency 	USD
pgv_pvi 	3989498880
pgv_si 	s5983857664
PHPSESSID 	n4fldjrsq7mtvi4mkl5o57ebau
Sessionempty
Server/Request Data USER 	www
HOME 	/home/www
PATH_TRANSLATED 	redirect:/index.php/admin/auth/passport/login.html/auth/passport/login.html
PATH_INFO 	/admin/auth/passport/login.html
SCRIPT_NAME 	/index.php
REQUEST_URI 	/index.php/admin/auth/passport/login.html
QUERY_STRING 	
REQUEST_METHOD 	GET
SERVER_PROTOCOL 	HTTP/1.1
GATEWAY_INTERFACE 	CGI/1.1
REMOTE_PORT 	23499
SCRIPT_FILENAME 	/www/wwwroot/22thinkbbs191022/public/index.php
SERVER_ADMIN 	webmaster@example.com
CONTEXT_DOCUMENT_ROOT 	/www/wwwroot/22thinkbbs191022/public
CONTEXT_PREFIX 	
REQUEST_SCHEME 	http
DOCUMENT_ROOT 	/www/wwwroot/22thinkbbs191022/public
REMOTE_ADDR 	115.171.132.248
SERVER_PORT 	80
SERVER_ADDR 	172.17.88.21
SERVER_NAME 	thinkbbs.cacbc.net
SERVER_SOFTWARE 	Apache
SERVER_SIGNATURE 	<address>Apache Server at thinkbbs.cacbc.net Port 80</address>
LD_LIBRARY_PATH 	/www/server/apache/lib
PATH 	/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/root/bin
HTTP_UPGRADE_INSECURE_REQUESTS 	1
HTTP_COOKIE 	thinkphp_show_page_trace=0|0; thinkphp_show_page_trace=0|0; thinkphp_show_page_trace=0|0; language=zh-cn; currency=USD; pgv_pvi=3989498880; thinkphp_show_page_trace=0|0; pgv_si=s5983857664; PHPSESSID=n4fldjrsq7mtvi4mkl5o57ebau
HTTP_CONNECTION 	keep-alive
HTTP_ACCEPT_ENCODING 	gzip, deflate
HTTP_ACCEPT_LANGUAGE 	zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
HTTP_ACCEPT 	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
HTTP_USER_AGENT 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
HTTP_HOST 	thinkbbs.cacbc.net
proxy-nokeepalive 	1
FCGI_ROLE 	RESPONDER
PHP_SELF 	/index.php/admin/auth/passport/login.html
REQUEST_TIME_FLOAT 	1571926608.0662
REQUEST_TIME 	1571926608
Environment Variablesempty
ThinkPHP Constants HTMLPURIFIER_PREFIX 	/www/wwwroot/22thinkbbs191022/vendor/ezyang/htmlpurifier/library
ThinkPHP V5.1.38 LTS
